### ISSUE TITLE
Error: Incompatible provider version - template deprecated

### ISSUE THREAD

**Issue by Y4nko** [iknowjason/AutomatedEmulation#2]
Hi Jason,

Thanks for sharing the project. 

I tried to run it on a Mac with M2 chip, but I kept getting the following error message, when I run the terraform init command.

`│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.`

Issue was resolved after I migrated from template_file to templatefile. I can commit the code changes.

Yanko

**Comment by iknowjason** [comment]
Hi @Y4nko thanks for sharing.  Please push a pr for commits and I'll review.  I need to make sure that doesn't break anything.  I'm on vacation so might be a few days for me to test.  Thx again for feedback.

**Comment by Y4nko** [comment]
Hi @iknowjason thanks, I have just created a pull request #3.

**Comment by iknowjason** [comment]
Hi @Y4nko Can you share with me the actual error showing that template_file did not work for you?  It works on my end.  I am just curious.  Your initial issue was an incompatible provider version for either terraform cli version or OS.  Just wanted to get some more information to understand.  Seems like two separate issues, but I can't see the other error you saw yet.

**Comment by Y4nko** [comment]
Hi @iknowjason, sure, this is the output of the command terraform init.

```
Initializing the backend...
Initializing modules...
Downloading registry.terraform.io/terraform-aws-modules/key-pair/aws 2.0.3 for key_pair...
- key_pair in .terraform/modules/key_pair

Initializing provider plugins...
- Finding latest version of hashicorp/http...
- Finding hashicorp/aws versions matching ">= 4.21.0, 4.61.0"...
- Finding hashicorp/tls versions matching ">= 3.4.0"...
- Finding latest version of hashicorp/local...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/template...
- Finding latest version of hashicorp/archive...
- Installing hashicorp/archive v2.4.2...
- Installed hashicorp/archive v2.4.2 (signed by HashiCorp)
- Installing hashicorp/http v3.4.3...
- Installed hashicorp/http v3.4.3 (signed by HashiCorp)
- Installing hashicorp/aws v4.61.0...
- Installed hashicorp/aws v4.61.0 (signed by HashiCorp)
- Installing hashicorp/tls v4.0.5...
- Installed hashicorp/tls v4.0.5 (signed by HashiCorp)
- Installing hashicorp/local v2.5.1...
- Installed hashicorp/local v2.5.1 (signed by HashiCorp)
- Installing hashicorp/random v3.6.2...
- Installed hashicorp/random v3.6.2 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```
<img width="1326" alt="image" src="https://github.com/iknowjason/AutomatedEmulation/assets/132595699/12b66c47-9dfb-43a9-a96d-81f757a2e971">

When I searched for use of template_file inside the code, I found the following lines of code that require template plugin which is deprecated.
<img width="384" alt="image" src="https://github.com/iknowjason/AutomatedEmulation/assets/132595699/a5a4fceb-51b2-4677-82e1-377df34310d3">

**Comment by iknowjason** [comment]
Thanks.  I still don't see where there is an error about the plugin not working - the older template plugin.  So what you are saying is, there wasn't an actual error about this?

Normally, terraform will show an obvious error and not build upon ```terraform apply```.  But what you are showing is an error with ```terraform init```.

**Comment by Y4nko** [comment]
Hi @iknowjason, this is an issue specific to Mac M1 chips, because there is no template package available for darwin_arm64. So, I can't get the required plugin using init before I can run terraform apply.
This is a known issue and the recommendation is to use templatefile function instead of template_file, which I did in the pull request.
[Issue #85 - Terraform provider archived](https://github.com/hashicorp/terraform-provider-template/issues/85)
Below is one of the linked issues to this.
[Changed usage of template provider to builtin templatefile function #64](https://github.com/hashicorp/terraform-google-consul/pull/64)
Same info can be found on template plugin page
[Template Provider](https://registry.terraform.io/providers/hashicorp/template/latest/docs#deprecation)

**Comment by iknowjason** [comment]
Thank you @Y4nko for the extra details.  Will test / verify / get this merged as soon as I can.

**Comment by iknowjason** [comment]
Thank you @Y4nko .  I have approved and merged.
