### ISSUE TITLE
Caldera Login 405 Method Not Allowed

### ISSUE THREAD

**Issue by MattRamsey** [iknowjason/AutomatedEmulation#5]
Hi there, 

Deployed BAS and Win1 instances via terraform, login screen for Caldera comes up on public IP on port 8888. Attempting to login with credentials from Terraform output but not getting past login screen.  

Ran Dev Tools and can see I'm getting a 405 Method Not Allowed in the request.  I tried from the Win1 instance via RDP and getting the same error from the Private IP on port 8888.  Thought it might be the haproxy.conf but thats not explicitly denying or defining any methods.  Something i've done wrong or perhaps something in the AWS config ?  I simply deployed with terraform apply --auto-approve

I'll keep investigating but just thought I'd reach out and see if anyone might know why

![image](https://github.com/iknowjason/AutomatedEmulation/assets/80547100/5f501001-6928-4141-b3f6-4fc8adbf91f5)

**Comment by iknowjason** [comment]
Hi @MattRamsey, thanks for reporting this.

Please do a pull from the latest code and let me know if it now works.  I fixed an issue yesterday:  
https://github.com/iknowjason/AutomatedEmulation/issues/4

The implementation broke from a Caldera change.  Now the transport should be https on port 8443.

**Comment by MattRamsey** [comment]
@iknowjason that worked and I'm able to login now.  Should've checked the repo activity more closely :) 

Thanks for the support, and for the project.  This is more than a considerable amount of effort
